baseURL = "/"
languageCode = "en-gb"
title = "JOHN T GRAY"

disableKinds = ["RSS"]
enableRobotsTXT = true
disableAliases = true

googleAnalytics = "UA-114350169-1"

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "JSON", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true
